### ISSUE TITLE
Get-CyAPI

### ISSUE THREAD

**Issue by enda-kelly** [jan-tee/cycli-examples#1]
Get-CyAPI -APIId 'XXXX' -APISecret 'XXX' -APITenantId 'XXXX'

Get-CyAPI : Cannot process argument transformation on parameter 'APISecret'. **Cannot convert the "XXXXX" value of type "System.String" to type
"System.Security.SecureString".**
At line:1 char:68
+ ... kk7x413k54' -APISecret 'XXXX' -APITen ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-CyAPI], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-CyAPI

###############################################################################

From what I can make out this relates to:
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($APISecret)

**Comment by jan-tee** [comment]
You just posted credentials to your environment on Github. I have removed the reference from your comments. Make sure you re-create the API account secrets immediately.

Regarding how to use it, the secret needs to be a SecureString. You can set that using Get-Credential. It is the standard way in Powershell to protect secrets.

Also, it is much better to use New-CyConsoleConfig and refer to the stored credentials than passing them directly. Just follow the examples from the module README (github.com/jan-tee/cycli).

**Comment by enda-kelly** [comment]
Thanks for the prompt reply to this, no worries regard the environmental credentials that were included in the original post, I ensured to adjust these accordingly before posting here.

Lessons have been learnt from past mistakes, I included “demo” data for the purposes for providing a complete issue.

Many thanks for the guide regards PSCredentials
