### ISSUE TITLE
Get all Scan Exclusions

### ISSUE THREAD

**Issue by chikme01** [jan-tee/cycli-examples#5]
How to get all Scan exclusions in place for a policy.
i.e., all exclusions under Protection Settings

**Comment by jan-tee** [comment]
The main README.md in this repository includes examples for how to get all script exclusions and all memory exclusions. When you look the output object of a the "Get-CyPolicy" (it's easiest to inspect when you convert it to JSON, e.g. using `| convertto-json` and then inspecting the resultant structure).

To get all scan exclusions for all policies, you would use:

`(get-cypolicylist | get-cypolicy).policy | where name -eq "scan_exception_list"`

it's not the nicest of possible ways, but it is how the API returns the policy object.

**Comment by chikme01** [comment]
This is how I am trying currently.
It is not the nicest out put again :(

$p = Get-CyPolicyList | where name -EQ  POLICY | Get-CyPolicy
$p.policy.value

**Comment by chikme01** [comment]
Thanks so much for looking into this for me
